### ISSUE TITLE
undefined is not an object(evaluating _reactNative.Keyboard.addListener)

### ISSUE THREAD

**Issue by swaroopa94** [Bolket/react-native-scrollview-smart#2]
Hi,
I am using your module but when i run my application i am getting an error as following
`undefined is not an object(evaluating _reactNative.Keyboard.addListener)`

React native version is: "^0.25.1"
 "react-native-scrollview-smart": "^0.1.0",

Can anyone help me in solving this

**Comment by sarovin** [comment]
Have you try with RN@0.36??
